export default {
    categories: "apps",
    money: "currency-usd",
    user: "account",
    email: "email",
    password: "lock",
    confirm_password:"lock-reset",
    message: "chat-processing",
    title: "border-color",
    star: "star",
    chevron: "chevron-right",
    trashcan: "trash-can",
    edit: "account-edit",
    recipes: "book-open-page-variant",
    logout: "logout",
    contact_us: "message-alert",
    search: "magnify",
    custom_search:"database-search",
    camera: "camera",
    camera_add: "camera-plus",
    google:"google",
    facebook:"facebook",
    new_recipe: "pen-plus",
    vegan: "leaf",
    gluten_free: "barley-off"
}